-- 11. Explique como você criaria uma tabela chamada "Clientes" com colunas para ID, nome, email, e data de nascimento. Inclua as restrições que julgar necessárias.

CREATE TABLE clientes (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- identificador unico para cada cliente, gerado de maneira automatica
    nome VARCHAR2(100) NOT NULL, -- nome do cliente: obrigatório para que nao fique em branco e com até 100 caracteres
    email VARCHAR2(100) NOT NULL UNIQUE, -- email do cliente: obrigatório para que nao fique em branco e unico para nao ter email duplicado
    data_nascimento DATE NOT NULL, -- data de nascimento do cliente, obrigatória para nao ficar em branco
    CHECK (data_nascimento <= SYSDATE) -- garante que a data de nascimento é anterior ou igual a data atual, fiz isso para ter coerencia de tempo
);

